CREATE TABLE APPOINTMENT_SPECIAL_SCHEDULES(
    PROFESSIONAL_SPECIAL_SCHEDULE_ID INT PRIMARY KEY,
    PROFESSIONAL_ID INT NOT NULL,
    APPOINTMENT_START_DATE DATE NOT NULL,
    APPOINTMENT_START_TIME TIME NOT NULL,
    APPOINTMENT_END_DATE DATE NOT NULL,
    APPOINTMENT_END_TIME TIME NOT NULL,
    SPECIAL_SCHEDULE_TYPE_ID INT NOT NULL,
    APPOINTMENT_PLACE_ID INT NOT NULL,
    ADD FOREIGN KEY(PROFESSIONAL_ID) REFERENCES PROFESSIONALS(PROFESSIONAL_ID)
    ADD FOREIGN KEY(APPOINMENT_PLACE_ID) REFERENCES APPOINTMENT_PLACES(APPOINMENT_PLACE_ID)
    ADD FOREIGN KEY(SPECIAL_SCHEDULE_TYPE_ID) REFERENCES SPECIAL_SCHEDULE_TYPES(SPECIAL_SCHEDULE_TYPE_ID)
)