CREATE TABLE PROFESSIONALS(
    PROFESSIONAL_ID INT PRIMARY KEY,
    PROFESSIONAL_NAME VARCHAR(50) NOT NULL,
    PROFESSIONAL_LAST_NAME VARCHAR(50) NOT NULL,
    PROFESSIONAL_BIRTH_DATE VARCHAR(50) NOT NULL,
    PROFESSIONAL_PHONE VARCHAR(20) NOT NULL,
    PROFESSIONAL_EMAIL VARCHAR(50) NOT NULL,
    PROFESSIONAL GENDER VARCHAR(1) NOT NULL,
    PROFESSIONAL_ADRESS VARCHAR(50) NOT NULL,
    PROFESSIONAL_COUNTRY VARCHAR(50) NOT NULL,
    PROFESSIONAL_DEPARTAMENT VARCHAR(50) NOT NULL,
    PROFESSIONAL_CITY VARCHAR(50) NOT NULL,
    PROFESSIONAL_TYPE_DOCUMENT VARCHAR(20) NOT NULL,
    PROFESSIONAL_DOCUMENT INT NOT NULL,
    PROFESSIONAL_REGISTRATION_NUMBER INT NOT NULL,
    OCCUPATION_ID INT NOT NULL,
    ADD FOREIGN KEY(OCCUPATION_ID) REFERENCES OCCUPATIONS(OCCUPATION_ID)
    
)
