CREATE TABLE PROFESSIONAL_SCHEDULES(
    PROFESSIONAL_SCHEDULE_ID INT PRIMARY KEY,
    PROFESSIONAL_ID INT NOT NULL,
    SCHEDULE_DAY DATE NOT NULL,
    START_TIME TIME NOT NULL,
    END_TIME TIME NOT NULL,
    APPOINMENT_PLACE_ID INT NOT NULL,
    ADD FOREIGN KEY(APPOINMENT_PLACE_ID) REFERENCES APPOINMENT_PLACES(APPOINMENT_PLACE_ID)
    ADD FOREIGN KEY(PROFESSIONAL_ID) REFERENCES PROFESSIONALS(PROFESSIONAL_ID)
)