CREATE TABLE APPOINTMENTS(
    APPOINTMENT_ID INT PRIMARY KEY,
    APPOINTMENT_DATE DATE NOT NULL,
    APPOINTMENT_DURATION VARCHAR(20) NOT NULL,
    APPOINTMENT_NOTES VARCHAR(50) NOT NULL,
    APPOINTMENT_START_TIME TIME NOT NULL,
    APPOINTMENT_END_TIME TIME NOT NULL,
    ADD FOREIGN KEY(PATIENT_ID) REFERENCES PATIENTS(PATIENT_ID)
    ADD FOREIGN KEY(PROFESSIONAL_ID) REFERENCES PROFESSIONALS(PROFESSIONAL_ID)
    ADD FOREIGN KEY(APPOINTMENT_TYPE_ID) REFERENCES APPOINTMENT_TYPES(APPOINTMENT_TYPE_ID)
    ADD FOREIGN KEY(APPPOINTMENT_STATUS_ID) REFERENCES APPOINTMENT_STATUS(APPPOINTMENT_STATUS_ID)
    ADD FOREIGN KEY(APPOINTMENT_PLACE_ID) REFERENCES APPOINTMENT_PLACES(APPOINTMENT_PLACE_ID)
    ADD FOREIGN KEY(APPOINTMENT_ORIGINAL_ID) REFERENCES APPOINTMENTS(APPOINTMENT_ID)
    
)

