CREATE TABLE APPOINTMENT_PLACES(
    APPOINMENT_PLACE_ID INT PRIMARY KEY,
    APPOINTMENT_PLACE_DESCRIPTION VARCHAR(50) NOT NULL,
    APPOINTMENT_PLACE_ADRESS VARCHAR(50) NOT NULL,
    APPOINMENT_PLACE_PHONE VARCHAR(20) NOT NULL,
    APPOINTMENT_PLACE_OFFICE INT NOT NULL,
    COUNTRY_ID INT NOT NULL,
    DEPARTAMENT_ID INT NOT NULL,
    CITY_ID INT NOT NULL,
    ADD FOREIGN KEY(COUNTRY_ID,DEPARTAMENT_ID,CITY_ID) REFERENCES CITIES(COUNTRY_ID,DEPARTAMENT_ID,CITY_ID)
)