CREATE TABLE DEPARTAMENTS(
    DEPARTAMENT_ID INT,
    DEPARTAMENT_NAME VARCHAR(100) NOT NULL,
    COUNTRY_ID INT,
    PRIMARY KEY(DEPARTAMENT_ID,COUNTRY_ID),
    FOREIGN KEY(COUNTRY_ID) REFERENCES COUNTRIES(COUNTRY_ID)
)


